name: 'Build Post Processor'
description: 'To update project settings after build is completed'
inputs:
  incrementBuildNumber:
    required: true
    description: 'Increment Build Number'
    default: false
runs:
  using: 'node16'
  main: 'dist/index.js'
